### ISSUE TITLE
Web access and CORS

### ISSUE THREAD

**Issue by skinofstars** [Skiddle/web-api#1]
Hi,

I've been trying to use your API through jQuery, but I'm getting `Access-Control-Allow-Origin`. Any chance of yourselves allowing access to `*`? Or will we need to setup a proxy or something.

Thanks :)

**Comment by bensebborn** [comment]
Hi,

The issue with any client side querying of the API, is that you could reveal your API key which is private. As such, we don't currently support client side access.

The best solution would be for you to pass through through a server side request (eg an Ajax request).

**Comment by skinofstars** [comment]
Great point. Thanks.
