### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by leighmullin** [Skiddle/web-api#12]
I'm developing for Alexa, and want Alexa to be able to say the date.  However, to do that I need your response to include a voice friendly converted date, rather than "2018-05-04".  Can you include a voice-friendly field for date so she can speak it?

**Comment by greg-js** [comment]
I've also been developing a voice interface for this. Read [this](https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html#say-as) for information on what to convert the date output to so Alexa will say it smoothly (although you may still have to deal with some exceptions).

A bit more tricky is date inputs for searching using voice, but [this library](https://github.com/niklongstone/amazon-date-parser) can help you out greatly for this.

**Comment by bensebborn** [comment]
The date formats are standard ISO formats so you should be able to interpret those. As @greg-js commented there's plenty of libraries available to support this.

Good luck!
