### ISSUE TITLE
Purchase Tickets

### ISSUE THREAD

**Issue by samnymr** [Skiddle/web-api#14]
Hiya, 

Is there any plans to allow us to use the api to complete a transaction?

Sam

**Comment by samnymr** [comment]
@bensebborn Is there any update on this?

**Comment by daparky** [comment]
Sorry for the late response.

We're considering this option, it's not a straight forward request and can become complicated when third party's are completing transactions on our behalf. I've marked this as a feature request.

Thanks.

**Comment by bensebborn** [comment]
Closing this issue, as you can use our 'Buy Tickets' html/javascript button to present checkout options to the user.

**Comment by IlyaShkurenko** [comment]
@bensebborn is there a way how i can include it in my flutter app? We need an option to purchase tickets via api or something similar.

**Comment by bensebborn** [comment]
Hi, sorry no, all transactions need to take place on Skiddle.

You can either link to Skiddle, or insert a ticket box widget into an HTML page which will show then the available ticket types, then redirect off to Skiddle to purchase.
