### ISSUE TITLE
Ticket Price

### ISSUE THREAD

**Issue by JonD1997** [Skiddle/web-api#15]
I am looking to display a ticket price from the API, however it is not clear what it is, it says in the API:

"entryprice":"From \u00a341"

what does this mean?

**Comment by OllieCrook** [comment]
Hi JonD1997,

The price being returned to you is a **Unicode escape sequence** followed by the number 41.

If we paste the [Unicode Escape Sequence into a decoder](http://sandbox.onlinephpfunctions.com/code/0db93a48f6d62b47562694880e9924f797d1f43f) we can see that ` \u00a3` is a `£`.

So you are technically recieving: `"entryprice":"From £41"`
