### ISSUE TITLE
Issues with Images in Manychat

### ISSUE THREAD

**Issue by Kwoochit** [Skiddle/web-api#16]
I'm creating a chatbot using Manychat incorporation Skiddle's API. 

I am pulling in the images into gallery card however the images are very pixelated - please see attached.
![IMG_13DFE4A0A554-1](https://user-images.githubusercontent.com/14979510/60461822-951ba380-9c3f-11e9-86d9-ce7ca4dd8ac5.jpeg)

Is there a fix for this?

Kind regards

**Comment by mysticalemon** [comment]
Assuming this is the events endpoint, there are 2 image URL fields in the response. If you try retrieving "largeimageurl" instead of "imageurl", this might help.
