### ISSUE TITLE
Event API 

### ISSUE THREAD

**Issue by shuyu-wu** [Skiddle/web-api#18]
Hi there,

May I ask how far does your data go back in the past? We're trying to retrieve the data before 2018 but nothing comes back, please let us know if there's data limitation with the API usage.

Thanks

**Comment by bensebborn** [comment]
Hi @shuyu-wu 

Although Skiddle has events data back to 2001, we don't expose this all in the API as our main focus is on future events. The API is really designed to encourage people to interact with upcoming events rather than as a historical log.

**Comment by shuyu-wu** [comment]
Hi @bensebborn 

Thanks for your reply, is there any chance to get the complete historical data? We would like to know if there's any room for a partnership. Also can you please reply me with an email? it's shuyu@eve.io

Thanks
Shuyu
