### ISSUE TITLE
Genre IDs and the Genres attached to them

### ISSUE THREAD

**Issue by BonkBoy** [Skiddle/web-api#19]
Hi,

I'm currently trying to use the API to get info back on Festivals based on the genres attached to them, but I can't find any information on what the genre IDs are that I need to pass in to filter based on Genre. Would you be able to point me towards them or send them through here?

Linking them on the readme next to the genre field of the events API example might be a good shout just for future reference as well.

Thanks!

**Comment by bensebborn** [comment]
You should be able to access the genres endpoint at /api/v1/genres. That will contain all the codes. 

We’ll add that to the docs, thanks.
