### ISSUE TITLE
More of a request than an issue .. Sorry!  (Genre request for night clubs)

### ISSUE THREAD

**Issue by Ggffarl** [Skiddle/web-api#2]
Hi Skiddle, 

Will it be possible for you to provide me a list of all the possible genres that a night club may play and their correct format ? 
e.g rnb OR RnB OR R&B ect. 

I received a bounce back email from apps@skiddle.com 

Best regards, 
Leon

**Comment by bensebborn** [comment]
Hi @Ggffarl ,

Yes of course, here you go:

House
Trance
UK Garage
R&B
Rock
Breaks
Drum n Bass
Techno
Deep/Soulful House
Retro House
Tribal House
Tech House
Acid House
Hard House
Psy/GoaTrance
Hardcore/Hardstyle
Old Skool
Pop
Club Classics
Funky House
Prog House
Dancehall
Jazz
Indie
Metal
Hard Trance
Electro
Cheesy Dance
Themed
Rap
Classical
Hip Hop
Blues
Ska
Acoustic
Soul
Folk
Funk
Alternative
Blues
Covers Band/Tribute Act
Salsa
Latin
Choral
Punk
Minimal Techno
Disco
Swing
Big Band
Rock & Roll
Electronic
80s
60s
70s
Dubstep
African
World Music
Reggae
Bassline
Grime
Country/Americana
Nu Rave
Opera
Spoken Word
Burlesque
Retro
Bass Music
EDM
Jungle
Hard Dance
