### ISSUE TITLE
Three Return field requests

### ISSUE THREAD

**Issue by scotchegg** [Skiddle/web-api#4]
HI There

Would it be possible to also return in the events results the flyer poster  image link ( currently only large), and also the user account id or some identifier that links events by the creators? Currently you return the event id and venue ids only. This would allow us to better manage the results sets, group them by accounts and setup some rules as per each accounts events for their future events.

Thank you :)

**Comment by bensebborn** [comment]
Hi @scotchegg 

I'm sure returning the flyer image would be possible.

Could you give us more info about your use case so can understand how you need to group events, please? There are several ways we can achieve this depending upon the use case.

Ben

**Comment by scotchegg** [comment]
HI Ben

Thank you for your reply.

Our application is very simply centred around the promotion of poster/flyer images of events, covering not just music but education, lifestyle and family events in your local area. So supplying us the flyer artwork where possible will be a great help for us to better showcase skiddle events for you and the promoters..

I appreciate not all promoters add the artwork, so in this case we we will manually research and add the artwork for the events if we can source it from promoters FB / web pages

In terms of managing the data fed into our db from your API we would like to be able to identify events on a per account/promoter level. So allowing us to manage their events better, adding images, linking other events and also helping to identify the same event only spread over different weeks or venues. 

It may also be that a specific promoter events may not be suitable for our application, so we could then easily prevent their events showing in our app or create specific rules. So after each download of latest information from you, their events will not appear. Alternatively they maybe perfect for our app and so we can highlight and make sure we support their and your events better. 

For example, in Birmingham "This is Tmrw", is a promoter ,thankfully he seems to put the name "This Is tmrw" in the event title, which could allow me to easily find, validate and put live his events. However if the event title like other accounts did not contain a similar string i could not as easily identify all his events.

Having a this unique account owner identifier will also help me put in place detection for events of the same promoter occurring each as regular events, and then allowing us to better manage how this appears to avoid duplication of artwork. 

I hope this helps.

**Comment by mikeskiddle** [comment]
Hi @scotchegg 

In regards to the verifying the promotor, you **should** be able to access the "promotorid" value in the resultset.

Hope this helps?

**Comment by scotchegg** [comment]
HI @mikeskiddle 

Thanks for your reply, however sadly there is no  "promotorid" field, we see only "id" under results which looks like event id, and also "id" under venue. i have attached the results of one event..
[example.txt](https://github.com/Skiddle/web-api/files/1310892/example.txt)

**Comment by mikeskiddle** [comment]
Ah, my mistake - admittedly I thought this was passed through.

As Ben has mentioned already we will look into adding this.

Thanks again!

**Comment by scotchegg** [comment]
Thanks @mikeskiddle .

If I could ask to assist us on planning on our work, do you happen to know if these changes maybe implemented in days, weeks or months?

Thanks

**Comment by scotchegg** [comment]
HI @mikeskiddle @bensebborn 

Sorry another request if possible.

Could you also please include the "eventcode" in the returned API, there is "genre" at the moment which I assume is the sub type of music(RnB, House etc), however your API does not tell us what top level type/category of event it is. 

So to recap, it would help a great deal to have "flyerimage", "promotorid" and "eventcode".

Thanks guys.

**Comment by scotchegg** [comment]
Hi Skiddle Team.

I see no action has been taken, so I will assume this is not going to be implemented?

If you cannot add these requests, it maybe mean we will exclude skiddle from our services, and use only Ticket Master , eventbrite and other ticket services, which would be such a shame. If there is anyway you can look to add the **poster/flyer image** field to the API this would be a great win for us and ultimately you.

Thanks for an update.
@bensebborn @mikeskiddle
