### ISSUE TITLE
Ability to access historical data

### ISSUE THREAD

**Issue by lewtur** [Skiddle/web-api#5]
Hi there, 

Are there any plans to add the ability to get event information for old events? I'm doing a university project aiming to try and predict how well a band is going to do based on a variety of data, and any historical data would be really useful.

I'm not talking years and years worth, maybe events from the last 3-6 months or something. 

Thanks

**Comment by bensebborn** [comment]
Currently this isn't supported as we focus our infrastructure on providing upcoming events
