### ISSUE TITLE
description parameter returns events with without artist/genre information.

### ISSUE THREAD

**Issue by calholmes7** [Skiddle/web-api#6]
Wiki states that, "description: (bool, optional) Passing this parameter will mean that your results will contain artist **and** genre information for each event". However, the parameter returns events with artist **or** genre, meaning that when parsing some events may still be missing either their artist or genre info even after passing description=1 into the query.

**Comment by bensebborn** [comment]
Both artist and genre information is not mandatory on all event types.

If you pass the param 'description=1' then this will be returned _if_ it's available. All music events should contain at least 1 music genre.
