### ISSUE TITLE
No useful ticket data being pulled through

### ISSUE THREAD

**Issue by JayBox325** [Skiddle/web-api#7]
I'm trying to pull through some ticket information so I can output a nicer responsive ticket listing for an event, yet the API seems to only have the following response regarding `tickets: ticketStatus: "2"` and `tickets: true`.

It'd be handy to get ticket price, ticket title etc with and without booking fees and a URL to your checkout.

Is this in the scope for the Skiddle API?

**Comment by bensebborn** [comment]
Hi,

These fields are currently for internal use only. We do have an XML file which details all this information so we may look to expose it on the API but it's not currently there.

Would the XML file work for you?
xml.skiddlecdn.co.uk/xml/affiliates/all.xml
