### ISSUE TITLE
Event search request no longer working

### ISSUE THREAD

**Issue by mogwai** [Skiddle/web-api#8]
I was using this request to get the events in London how longer its stopped working:

Request ID = api_5aa65b4ccd86d3.95358625

https://www.skiddle.com/api/v1/events/search/?api_key=abdefghijklmnop&latitude=0.1278&longitude=51.5074&limit=100&radius=45

**Comment by bensebborn** [comment]
Hi,

We can look into this for you. I'm presuming you're using an actual API Key and not the dummy text 'abcd..' above?

If you can let me know what time window you made the request above (api_5aa65b4ccd86d3.95358625) we can check the logs.

**Comment by mogwai** [comment]
I made the request this morning in the last hour.

Yes that isn't my real API key

**Comment by bensebborn** [comment]
Looks as though your lat/long are the wrong way around

That location is in the middle of the Indian Ocean...

https://www.darrinward.com/lat-long/?id=5aa661c2d8b303.11267963

This works as expected:

https://www.skiddle.com/api/v1/events/search/?api_key=[APIKEY]&latitude=51.5074&longitude=0.1278&radius=45
